import './globals.css'
import { Inter } from 'next/font/google'
import Slidebar from './Slidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shoppersprey Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex h-screen bg-gray-100">
        <Slidebar />
        <main className="ml-8 flex-grow flex-1 overflow-y-auto bg-gray-100">{children}</main>
      </body>
    </html>
  );
}
