import './globals.css'
import { Inter } from 'next/font/google'
import Slidebar from './Slidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shoppersprey Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Slidebar />
        <main>{children}</main>
      </body>
    </html>
  );
}
